// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use remote Supabase temporarily to debug loading issue
const SUPABASE_URL = "https://ilpwuimcwhforithmmee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlscHd1aW1jd2hmb3JpdGhtbWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTYwNzcsImV4cCI6MjA3MDI3MjA3N30.I6rqy8wCOy9QH2t0rwC0YPpPZJMnM4zijlFAwAV4q8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});